#bind 127.0.0.1
#protected-mode yes
#port 6379
#daemonize no
#loglevel notice
#logfile "d:/PROFILE DATA/Desktop/opencode/snakehead/logs/memurai-local.log"
#dir "d:/PROFILE DATA/Desktop/opencode/snakehead/logs"
#dbfilename "memurai-local.rdb"
